apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: my-app
  labels:
    app: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: shybalghosh101/login-app:1.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: node-app-secrets
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-app-secrets
                  key: mongo-root-password
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: my-app
spec:
  selector:
    app: node-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
