apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: my-app
  labels:
    app: mongo-pv
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/data/mogno"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: mongo-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      request:
        storage: 1Gi